Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from folium import GeoJson

m = folium.Map([49.553726,18.017578], 
            zoom_start=4)

cp = folium.Choropleth(
    geo_data= '',
    data= '' ,
    columns=[],
    key_on="",
    fill_color="YlGn",
    fill_opacity=0.7,
    line_opacity=0.1,
    nan_fill_color = '' ,
    nan_fill_opacity = 0 ,
    legend_name="pisa score"
).add_to(m)

folium.GeoJsonTooltip(['NAME'] , labels=False ).add_to(cp.geojson)

m.save('pisa.html')
m
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
[0;32m/var/folders/nf/35gdwksd0fx8kzbsljz4dz6hnrcnxq/T/ipykernel_87751/2523040103.py[0m in [0;36m<module>[0;34m[0m
[1;32m     14[0m     [0mnan_fill_color[0m [0;34m=[0m [0;34m''[0m [0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m     [0mnan_fill_opacity[0m [0;34m=[0m [0;36m0[0m [0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 16[0;31m     [0mlegend_name[0m[0;34m=[0m[0;34m"pisa score"[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     17[0m ).add_to(m)
[1;32m     18[0m [0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/folium/features.py[0m in [0;36m__init__[0;34m(self, geo_data, data, columns, key_on, bins, fill_color, nan_fill_color, fill_opacity, nan_fill_opacity, line_color, line_weight, line_opacity, name, legend_name, overlay, control, show, topojson, smooth_factor, highlight, **kwargs)[0m
[1;32m   1292[0m                 [0mstyle_function[0m[0;34m=[0m[0mstyle_function[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1293[0m                 [0msmooth_factor[0m[0;34m=[0m[0msmooth_factor[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1294[0;31m                 highlight_function=highlight_function if highlight else None)
[0m[1;32m   1295[0m [0;34m[0m[0m
[1;32m   1296[0m         [0mself[0m[0;34m.[0m[0madd_child[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mgeojson[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/folium/features.py[0m in [0;36m__init__[0;34m(self, data, style_function, highlight_function, name, overlay, control, show, smooth_factor, tooltip, embed, popup, zoom_on_click, marker)[0m
[1;32m    495[0m         [0mself[0m[0;34m.[0m[0mmarker[0m [0;34m=[0m [0mmarker[0m[0;34m[0m[0;34m[0m[0m
[1;32m    496[0m [0;34m[0m[0m
[0;32m--> 497[0;31m         [0mself[0m[0;34m.[0m[0mdata[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mprocess_data[0m[0;34m([0m[0mdata[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    498[0m [0;34m[0m[0m
[1;32m    499[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0mstyle[0m [0;32mor[0m [0mself[0m[0;34m.[0m[0mhighlight[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/folium/features.py[0m in [0;36mprocess_data[0;34m(self, data)[0m
[1;32m    526[0m                     [0mself[0m[0;34m.[0m[0membed_link[0m [0;34m=[0m [0mdata[0m[0;34m[0m[0;34m[0m[0m
[1;32m    527[0m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mget_geojson_from_web[0m[0;34m([0m[0mdata[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 528[0;31m             [0;32melif[0m [0mdata[0m[0;34m.[0m[0mlstrip[0m[0;34m([0m[0;34m)[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;32min[0m [0;34m'[{'[0m[0;34m:[0m  [0;31m# This is a GeoJSON inline string[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    529[0m                 [0mself[0m[0;34m.[0m[0membed[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    530[0m                 [0;32mreturn[0m [0mjson[0m[0;34m.[0m[0mloads[0m[0;34m([0m[0mdata[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mIndexError[0m: string index out of range
IndexError: string index out of range

